### ISSUE TITLE
download from git did not work

### ISSUE THREAD

**Issue by vkuehn** [dr-jerry/iPath#1]
Hello,

after downloading iPath I was not able to run the the index.html as it can be seen on http://www.stretchsketch.com/. 
some of the js scripts are not in the paths expected. It would be good if iPath is just runnable after git cloning it

If you like I can help here . Actually I search for the possibility to create 2D Objects as in OpenJsCad 

Thanks and regards,
Volker

**Comment by dr-jerry** [comment]
Hi Volker thanks for your interest! You're the first one complaining and also possible the first one to download this library.
I actually only want to disclose the javascript libraries for iPath in this github project. The stretchsketch.com is a bit of polluted spaghetti code of which I'm not particular proud of.
iPath also needs a lot of shaving but it is more meant as an independent javascript library for inclusion in your own project or website. 
Of course this does not justify the defunct index.html page which should be fixed. I would like to fix (or have it fixed :-) with only dependencies to iPath to stress the fact that iPath is an independent library.

I do think that iPath.js is worth examining for creating or scripting customizable 2D objects. As examples for iPath you can,in stretchsketch.com, disclose the code for the models with the link "edit" to see how iPath is used and experiment yourself.

I'm quite busy right now with courses, work, family etc. The index.html fix is still on my backlog and might be prioritized when demand increases.

Jeroen.

**Comment by vkuehn** [comment]
Hi Jeroen,

thanks explaining the real intention of iPath. I think the issue can be therefore simply closed.

However after looking around in your code I think all I really need is what is in you iscriptdesign project and what you have done with jsvg. Is that something you have invcented or can I look elsewhere for more insights ?

Thanks,
Volker
