### ISSUE TITLE
What does it do? Looking for a solution.

### ISSUE THREAD

**Issue by cojarbi** [dr-jerry/iPath#2]
Hi. Im looking for a solution to read layers from SVG or DXF on the browser via JS. This could really lead to a much easier workflow here github.com/openhardwarecoza/LaserWeb3

**Comment by dr-jerry** [comment]
Hi cojarbi, sorry I think I saw your mail a few days back, but I think I forgot. Not sure iPath is what your looking for. iPath is a javascript, graphics specific language for generating SVG and DXF in your browser. Reading SVG via Javascript on the browser should not be a problem, I'm not aware of any javascript for reading, parsing and rendering DXF in the browser. For iPath's capabilities have a look at www.stretchsketch.com.
PS thanks for the star!

**Comment by ghost** [comment]
@cojarbi -  i finished our layer code yesterday.  The issue wasnt reading layers.  The issue with svg is parsing that relative positioning attribute,  over multiple layers.   For dxf we are all sorted.    Ps,  sorry about hijacking thead.  We have working JS based import of all these on Github.com/openhardwarecoza/LaserWeb3 (stl,  svg,  dxf,  bitmap,  gcode)
